name: Coupon CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Change Permissions
      run: chmod +x ./gradlew 
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with: 
        name: coupon-engine-app
        path: build/libs/coupon_engine-1.2.0.jar
        
  deploy:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: coupon-engine-app
      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: coupon-engine-app
          environment_name: coupon-engine-app
          version_label: ${{ github.SHA }}
          region: sa-east-1
          deployment_package: coupon_engine-1.2.0.jar
